environments:
  dev:
    aws_region: "ap-southeast-1"
    vpc_cidr: "10.0.0.0/16"
    az_count: 2
    db_username: "boolean_admin"
    ecs_environment:
      - name: "APP_ENV"
        value: "development"
      - name: "DATABASE_URL"
        value: "postgres://dev_user:dev_pass@dev_host:5432/dev_db"
    
  prod:
    aws_region: "ap-southeast-1"
    vpc_cidr: "10.1.0.0/16"
    az_count: 2
    db_username: "boolean_admin"
    ecs_environment:
      - name: "APP_ENV"
        value: "production"
      - name: "DATABASE_URL"
        value: "postgres://prod_user:prod_pass@prod_host:5432/prod_db"