plan-dev:
	terraform plan -var-file=environments/dev.tfvars
plan-prod:
	terraform plan -var-file=environments/prod.tfvars

apply-dev:
	terraform apply -var-file=environments/dev.tfvars
apply-prod:
	terraform apply -var-file=environments/prod.tfvars
